=== gvgreat/usecase-point/src/org/ucp/uaw/unadjusted-actor-weights.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 2 (http://www.altova.com) by G. Vaidhyanathan  -->
<!--W3C Schema generated by XMLSpy v2010 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="unadjusted-actor-weights">
		<xs:annotation>
			<xs:documentation>
				Unadjusted Use Case Weights involved in Use Case Point Estimation. Currently 3 UUCWs are identified.	
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="actor-weight" maxOccurs="unbounded"/>
				<xs:element ref="total-UAW"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="actor-weight">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type"/>
				<xs:element name="description" type="xs:string" nillable="false"/>
				<xs:element ref="weight"/>
				<xs:element ref="num-actors"/>
				<xs:element ref="result"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Simple"/>
				<xs:enumeration value="Average"/>
				<xs:enumeration value="Complex"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="num-actors">
		<xs:simpleType>
			<xs:restriction base="xs:double">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="weight">
		<xs:simpleType>
			<xs:restriction base="xs:double">
				<xs:enumeration value="1"/>
				<xs:enumeration value="2"/>
				<xs:enumeration value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="result">
		<xs:simpleType>
			<xs:restriction base="xs:double">
				<xs:minInclusive value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="total-UAW">
		<xs:simpleType>
			<xs:restriction base="xs:double"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== gvgreat/usecase-point/src/org/ucp/uaw/unadjusted-actor-weights.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="unadjusted-actor-weights.xslt"?>
<unadjusted-actor-weights xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="unadjusted-actor-weights.xsd">
<actor-weight>
		<type>Simple</type>
		<description>The Actor represents another system with a defined API.</description>
		<weight>1</weight>
		<num-actors>0</num-actors>
		<result>0</result>
	</actor-weight>
	<actor-weight>
		<type>Average</type>
		<description>The Actor represents another system interacting through a protocol, like TCP/IP.</description>
		<weight>2</weight>
		<num-actors>0</num-actors>
		<result>0</result>
	</actor-weight>
	<actor-weight>
		<type>Complex</type>
		<description>The Actor is a person interacting via an interface.</description>
		<weight>3</weight>
		<num-actors>0</num-actors>
		<result>0</result>
	</actor-weight>
	<total-UAW>0</total-UAW>
</unadjusted-actor-weights>
