=== gvgreat/usecase-point/src/org/ucp/tcf/technical-complexity-factors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 2 (http://www.altova.com) by G. Vaidhyanathan  -->
<!--W3C Schema generated by XMLSpy v2010 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="technical-complexity-factors">
		<xs:annotation>
			<xs:documentation>
				Technical Complexity Factors involved in Use Case Point Estimation. Currently 13 TCFs are identified, and more can be added.	
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="technical-factor" maxOccurs="unbounded"/>
				<xs:element ref="total-value" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="calculated-tcf" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="technical-factor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="factor"/>
				<xs:element name="description" type="xs:string" nillable="false"/>
				<xs:element ref="weight"/>
				<xs:element ref="complexity"/>
				<xs:element ref="calculated-factor"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="factor">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[T]([0-9])*"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="complexity">
		<xs:simpleType>
			<xs:restriction base="xs:double">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="5"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="weight">
		<xs:simpleType>
			<xs:restriction base="xs:double">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="5"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="calculated-factor">
		<xs:simpleType>
			<xs:restriction base="xs:double">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="25"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="total-value">
		<xs:simpleType>
			<xs:restriction base="xs:double"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="calculated-tcf">
		<xs:simpleType>
			<xs:restriction base="xs:double"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== gvgreat/usecase-point/src/org/ucp/tcf/technical-complexity-factors.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="technical-complexity-factors.xslt"?>
<technical-complexity-factors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="technical-complexity-factors.xsd">
	<technical-factor>
		<factor>T1</factor>
		<description>Distributed System</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T2</factor>
		<description>Performance</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T3</factor>
		<description>End User Efficiency</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T4</factor>
		<description>Complex internal Processing</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T5</factor>
		<description>Reusability</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T6</factor>
		<description>Easy to install</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T7</factor>
		<description>Easy to use</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T8</factor>
		<description>Portable</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T9</factor>
		<description>Easy to change</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T10</factor>
		<description>Concurrent</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T11</factor>
		<description>Special security features</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T12</factor>
		<description>
			Provides direct access for third parties
		</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<technical-factor>
		<factor>T13</factor>
		<description>
			Special user training facilities are required
		</description>
		<weight>0</weight>
		<complexity>0</complexity>
		<calculated-factor>0</calculated-factor>
	</technical-factor>
	<total-value>0</total-value>
	<calculated-tcf>0</calculated-tcf>
</technical-complexity-factors>
