=== gvgreat/usecase-point/src/org/ucp/ecf/environment-complexity-factors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 2 (http://www.altova.com) by G. Vaidhyanathan -->
<!--W3C Schema generated by XMLSpy v2010 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="environment-complexity-factors">
		<xs:annotation>
			<xs:documentation>
				Environment Complexity Factors involved in Use Case Point Estimation. Currently 13 ECFs are identified, and more can be added.	
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="environment-factor" maxOccurs="unbounded"/>
				<xs:element ref="total-value"/>
				<xs:element ref="calculated-ecf"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="environment-factor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="factor"/>
				<xs:element name="description" type="xs:string" nillable="false"/>
				<xs:element ref="weight"/>
				<xs:element ref="impact"/>
				<xs:element ref="calculated-factor"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="factor">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[E]([0-9])*"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="impact">
		<xs:simpleType>
			<xs:restriction base="xs:double">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="5"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="weight">
		<xs:simpleType>
			<xs:restriction base="xs:double">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="5"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="calculated-factor">
		<xs:simpleType>
			<xs:restriction base="xs:double">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="25"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="total-value">
		<xs:simpleType>
			<xs:restriction base="xs:double"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="calculated-ecf">
		<xs:simpleType>
			<xs:restriction base="xs:double"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== gvgreat/usecase-point/src/org/ucp/ecf/environment-complexity-factors.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="environment-complexity-factors.xslt"?>
<environment-complexity-factors
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="environment-complexity-factors.xsd">
	<environment-factor>
		<factor>E1</factor>
		<description>Familiarity with UML</description>
		<weight>0</weight>
		<impact>0</impact>
		<calculated-factor>0</calculated-factor>
	</environment-factor>
	<environment-factor>
		<factor>E2</factor>
		<description>Application Experience</description>
		<weight>0</weight>
		<impact>0</impact>
		<calculated-factor>0</calculated-factor>
	</environment-factor>
	<environment-factor>
		<factor>E3</factor>
		<description>Object Oriented Experience</description>
		<weight>0</weight>
		<impact>0</impact>
		<calculated-factor>0</calculated-factor>
	</environment-factor>
	<environment-factor>
		<factor>E4</factor>
		<description>Lead analyst capability</description>
		<weight>0</weight>
		<impact>0</impact>
		<calculated-factor>0</calculated-factor>
	</environment-factor>
	<environment-factor>
		<factor>E5</factor>
		<description>Motivation</description>
		<weight>0</weight>
		<impact>0</impact>
		<calculated-factor>0</calculated-factor>
	</environment-factor>
	<environment-factor>
		<factor>E6</factor>
		<description>Stable Requirements</description>
		<weight>0</weight>
		<impact>0</impact>
		<calculated-factor>0</calculated-factor>
	</environment-factor>
	<environment-factor>
		<factor>E7</factor>
		<description>Part-time workers</description>
		<weight>0</weight>
		<impact>0</impact>
		<calculated-factor>0</calculated-factor>
	</environment-factor>
	<environment-factor>
		<factor>E8</factor>
		<description>Difficult Programming language</description>
		<weight>0</weight>
		<impact>0</impact>
		<calculated-factor>0</calculated-factor>
	</environment-factor>
	<total-value>0</total-value>
	<calculated-ecf>0</calculated-ecf>
</environment-complexity-factors>
